<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" href="/favicon.svg" type="image/x-icon">
    <link rel="stylesheet" href="style.css">
    <title>Document</title>
</head>
<body>
    <div id="gameboy">
        <div id="display">
            <?php if (isset($data)) { ?>
                <div>
                    <h2>Résultat du match</h2>
                    <h3>Gagnant du match : <?= $winner->getName() ?></h3>
                    <p>Avec comme président : <?= $winner->getPresident()->getFullName() ?></p>
                </div>
            <?php } else { ?>
                <div>
                    <h2>Pas de résultats</h2>
                </div>
            <?php } ?>
            <div>
                <a href="?q=newPresident"><input type="button" value="Ajoutez president"></a>
            </div>
        </div>
        <div id="control">
            <div id="direction">
                <div id="direction-up"></div>
                <div id="direction-right"></div>
                <div id="direction-down"></div>
                <div id="direction-left"></div>
            </div>
            <div id="button">
                <div id="button-a"></div>
                <div id="button-b"></div>
            </div>
        </div>
    </div>
</body>
</html>