<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Ajout d'un président</title>
</head>
<body>
    <form action="" method="post">
        <label for="firstName">Prénom du président :</label>
        <input type="text" name="firstName" id="">
        <label for="lastName">Nom du président</label>
        <input type="text" name="lastName" id="">
        <label for="country">Pays du président :</label>
        <input type="text" name="country" id="">
        <label for="life">Vie du président :</label>
        <input type="number" name="life" id="">
        <label for="strength">Force du président :</label>
        <input type="number" name="strength" id="">
        <input type="submit" value="Envoyez">
    </form>
</body>
</html>