<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" href="/favicon.svg" type="image/x-icon">
    <title>Président <?= $president['firstName'] ?> <?= $president['lastName'] ?></title>
</head>
<body>
    <h1><?= $president['firstName'] ?> <?= $president['lastName'] ?></h1>

    <div>
        Président de <?= $president['country'] ?>
    </div>


    <dl>
        <dt>Point de vie</dt><dd><?= $president['life'] ?></dd>
        <dt>Force</dt><dd><?= $president['strength'] ?></dd>
    </dl>

</body>
</html>